print("Selamat datang")
nama = input("Masukan nama anda : ")
NIM = input("Masukan NIM anda : ")
umur = input("Masukan Umur anda : ")
print(f"Halo {nama} dengan NIM {NIM} dan umur anda adalah {umur} Tahun")
